### ISSUE TITLE
VQA: Attending - Event

### ISSUE THREAD

**Issue by jcreech83** [GoogleChrome/ioweb2016#493]
- [x] intro card copy specs across all sizes: 24/32
- [ ] card padding: same on all four sides
- [x] intro copy padding: 2x that of normal card padding
- [ ] need consistent subheads (sandbox, code labs, etc) across all sizes: 24px
- [ ] need consistent body copy across all sizes: 16/24
- [x] subheads: bottom margin: 8px
- [x] fullscreen map: 96% bg opacity
- [x] fullscreen map: regular web content shouldn’t be scrollable

@paulfarning @jeffposnick

**Comment by atishpatel** [comment]
@ebidel or @paulfarning : The project has paper dialogs inside on pages and still manages to have expected behavior with iron overlay. If you have some spare time, could you please comment on how the io2016 project got around the paper dialog and iron overlay issue? https://github.com/PolymerElements/paper-dialog/issues/7

**Comment by ebidel** [comment]
Not sure what the overlay issues are but we're not using paper-header-panel, but the app-layout elements instead (https://elements.polymer-project.org/elements/app-layout). Not sure if that's the issue though, but generally, those newer elements try to do less magic.

We also only show the dialog once the page is setup, has layout, etc. That could be some of the overlay issues if you try to show the overlay too soon.
